### ISSUE TITLE
journey maps waypoint issue

### ISSUE THREAD

**Issue by Josh65-2201** [Spectre0987/tardis-1.12-issues#11]
The waypoint beacon goes through all the blocks when it not meant to. It happens when the tardis BOTI is in view. I have also tried with and without optifine and it still happens.

![2020-02-28_20 11 28](https://user-images.githubusercontent.com/26977075/75584618-05e1bc80-5a68-11ea-9842-13e296653db2.png)

![2020-02-28_20 11 39](https://user-images.githubusercontent.com/26977075/75584621-07ab8000-5a68-11ea-9fe2-0b9daf348123.png)

**Comment by Spectre0987** [comment]
This is due to the BOTI effect, and unfortunately I can't fix one without breaking the other

**Comment by Josh65-2201** [comment]
Ok thanks
