### ISSUE TITLE
Tardis mod interferes with other mods dimensions

### ISSUE THREAD

**Issue by Someone-193** [Spectre0987/tardis-1.12-issues#12]
dimension 2 which the tardis mod uses interferes with an AE2 dimension. Solution: change the dimension so people can have an ae2 system in there tardis

**Comment by Spectre0987** [comment]
Our dimensions are assigned dynamically, AE2's are not. When our mod gets loaded first, AE2 tries to take what ever dimension is set in it's config, regardless of whether it's been claimed or not. You can fix this by changing the dimension ID in AE2's config
