### ISSUE TITLE
0.0.3 - Artron Update!  error multiplayer

### ISSUE THREAD

**Issue by TwilightGamerPro** [Spectre0987/tardis-1.12-issues#14]
Causes some player's to auto disconnect but it gives this code from the tardis mod before they fully get booted. [net.tardis.mod.network.packets.MessageConfigSync:<init>:21]: [64xtile.tardis.toyota_hexagon_1@0] we've tried everything from resetting configs, generating new worlds, tried different forge with still in 1.12.2 and still causes the same issues.

**Comment by Spectre0987** [comment]
Please use use https://pastebin.com and give me a full log. That message is intended and doesn't show anything

**Comment by TwilightGamerPro** [comment]
We fixed it, it seemed to have been a miss version, of 1.12.2 forge as it seemed this one needed the 2847 to work so it doesn't kick other players out of their own tardis,

**Comment by Spectre0987** [comment]
Ah, neat
