### ISSUE TITLE
Tardis Dimension breaks game

### ISSUE THREAD

**Issue by Oonicorn** [Spectre0987/tardis-1.12-issues#17]
Upon entering the TARDIS, the game doesn't really work properly anymore. Nothing except blocks can be interacted with, commands and chat messages do not go through, and attempting to return to the title screen causes the game to stop responding indefinitely.

**Comment by Spectre0987** [comment]
I assume you have Ice and Fire installed?

**Comment by Oonicorn** [comment]
Oh wow, yeah, I do. I guess this is a known issue. Is there any way to fix the issue without removing one of the mods or are they inherently incompatible?

**Comment by Spectre0987** [comment]
I have no idea. Ice and Fire seems to want to generate things in my dimension, which it can't. This seems to throw it for a loop and it hangs the server. There might be a way to blacklist dimensions in their config, if not one will have to go
