### ISSUE TITLE
Atron bank depleting speed setting in the config

### ISSUE THREAD

**Issue by Josh65-2201** [Spectre0987/tardis-1.12-issues#4]
It would be nice to increase the time for the artron banks depleting in the config. As in I can make flight lose 1% of artron energy every 10 sec and force field every 5 sec.

**Comment by boot2big** [comment]
"Speed Factor"

**Comment by Spectre0987** [comment]
You can kinda do this after the artron re-write coming for 1.12

**Comment by Josh65-2201** [comment]
Ok cool.
