### ISSUE TITLE
Add an option to turn off optifine warning

### ISSUE THREAD

**Issue by Josh65-2201** [Spectre0987/tardis-1.12-issues#8]

**Comment by Spectre0987** [comment]
No

**Comment by Josh65-2201** [comment]
Why not?

**Comment by boot2big** [comment]
even though if you leave the mouse in the wrong position, minecraft will find a way to automatically click it and instantly quit... this is a forge issue, but the page is annoying and some people are willing to put up with the visual issues/crashes instead of fps drops

**Comment by Josh65-2201** [comment]
How does this relate to warning screen coming up on every launch of minecraft? Other mods with the same system has way of turning it off in the config. Even if it not possible it could be changed to chat and then have a turn off option.

**Comment by boot2big** [comment]
it does relate due to the Weird click activating the close game button. Why is it there?
Maybe it should just remove the close game button and to close the game you continue to the main screen

**Comment by ghost** [comment]
Yes please set an option for this be turned off, I can't tell you how many times I've either had to restart a 15 minute modpack load OR, almost had to.
