### ISSUE TITLE
dalek invasions issues

### ISSUE THREAD

**Issue by Josh65-2201** [Spectre0987/tardis-1.12-issues#9]
I have asked this up on cruse forge after getting the advise to remove optifine. I have recently tested this and it didn't crash but still did not work.

Daleks still died instantly and companions won't be in the tardis after telling them to go in there. Also when telling them to get the tardis it will only move 2 block from it original position not to where I am (about 12 blocks away).

[latest.log](https://github.com/Spectre0987/tardis-1.12-issues/files/4246785/latest.log)

**Comment by Spectre0987** [comment]
Entities dying when they enter the TARDIS is a known bug, fixed in as-yet unrealeased Artron Update (0.1.3)

**Comment by Spectre0987** [comment]
What do you mean they died? Do they just disappear or do they show particles and stuff?

**Comment by ghostbuster3210** [comment]
I believe the entities fall through the floor and into the void, as entities that follow you such as wolves or MCA villagers have been able to enter my tardis in the current version because if they get too far away they teleport back.

**Comment by Josh65-2201** [comment]
They do the death animation where the fall over and turn to smoke particles. I have also looked around for other entities killing them but haven't found any.
